version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somemoodle
      MYSQL_DATABASE: bitnami_moodle
      MYSQL_USER: bn_moodle
      MYSQL_PASSWORD: 5c8be958b7

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9997:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somemoodle

  moodle:
    build: .
    depends_on:
      - db
    ports:
      - "9998:80"
    restart: always
    environment:
      DB_ENV_MYSQL_DATABASE: bitnami_moodle
      DB_ENV_MYSQL_USER: bn_moodle
      DB_ENV_MYSQL_PASSWORD: 5c8be958b7
      DB_PORT_3306_TCP_ADDR: db:3306
      MOODLE_URL: http://lms2.abc.com
    volumes:
      - ./moodledata:/var/moodledata